import { useRef } from 'react';
import { useParams, Link } from 'react-router-dom';
import type { AppState } from '../types';
import { formatDate, formatCurrency, listTotalCost, groupByCategory, exportToCSV, storeLabel } from '../utils';
import StoreBadge from '../components/StoreBadge';

interface ShareListProps {
  state: AppState;
}

export default function ShareList({ state }: ShareListProps) {
  const { id } = useParams<{ id: string }>();
  const printRef = useRef<HTMLDivElement>(null);

  const list = state.lists.find(l => l.id === id);

  if (!list) {
    return (
      <div className="text-center py-16">
        <div className="text-4xl mb-4">😕</div>
        <h2 className="text-xl font-semibold mb-2">List not found</h2>
        <Link to="/" className="text-sams hover:underline">← Back to Dashboard</Link>
      </div>
    );
  }

  const total = listTotalCost(list);
  const grouped = groupByCategory(list.items);
  const shareUrl = `${window.location.origin}/list/${list.id}`;
  const accentColor = list.store === 'ht' ? '#00843D' : '#004990';

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = async () => {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });

    let y = 40;
    const left = 40;
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(accentColor);
    doc.text(list.name, left, y);
    y += 24;

    doc.setFontSize(10);
    doc.setTextColor('#6C757D');
    doc.text(`Week of ${formatDate(list.weekOf)} · ${storeLabel(list.store)} · Est. Total: ${formatCurrency(total)}`, left, y);
    y += 24;

    // Items by category
    for (const [category, items] of Object.entries(grouped)) {
      if (y > 700) { doc.addPage(); y = 40; }

      doc.setFontSize(12);
      doc.setTextColor(accentColor);
      doc.text(category, left, y);
      y += 6;
      doc.setDrawColor(accentColor);
      doc.line(left, y, pageWidth - 40, y);
      y += 14;

      doc.setFontSize(10);
      doc.setTextColor('#212529');

      for (const item of items) {
        if (y > 720) { doc.addPage(); y = 40; }
        const check = item.checked ? '✓ ' : '☐ ';
        doc.text(`${check}${item.name}`, left + 8, y);
        doc.text(`${item.quantity} ${item.unit}`, pageWidth - 180, y);
        doc.text(formatCurrency(item.approxCost * item.quantity), pageWidth - 80, y, { align: 'right' });
        y += 16;
      }
      y += 8;
    }

    // Footer
    y = Math.max(y, 700);
    doc.setFontSize(9);
    doc.setTextColor('#6C757D');
    doc.text(`Generated by Family Grocery Tracker · ${new Date().toLocaleDateString()}`, left, 750);

    doc.save(`grocery-list-${list.weekOf}.pdf`);
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl).then(() => {
      alert('Link copied to clipboard!');
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <Link to={`/list/${list.id}`} className="text-xs text-brand-muted hover:text-sams block mb-1">
            ← Back to List
          </Link>
          <h1 className="text-xl font-bold text-brand-text">Share & Export</h1>
        </div>
        <StoreBadge store={list.store} size="md" />
      </div>

      {/* Share Actions */}
      <div className="bg-white rounded-xl border border-brand-border p-4 shadow-sm space-y-3">
        <h2 className="font-semibold text-sm text-brand-text">Export Options</h2>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-brand-bg border border-brand-border rounded-lg text-sm font-medium hover:bg-gray-100 transition-colors"
          >
            🖨️ Print
          </button>
          <button
            onClick={handleExportPDF}
            className="px-4 py-2 bg-sams text-white rounded-lg text-sm font-medium hover:bg-sams-dark transition-colors"
          >
            📄 Export PDF
          </button>
          <button
            onClick={() => exportToCSV(list)}
            className="px-4 py-2 bg-white border border-brand-border rounded-lg text-sm font-medium hover:bg-brand-bg transition-colors"
          >
            📊 Export CSV
          </button>
          <button
            onClick={handleCopyLink}
            className="px-4 py-2 bg-white border border-brand-border rounded-lg text-sm font-medium hover:bg-brand-bg transition-colors"
          >
            🔗 Copy Link
          </button>
        </div>
        <div className="bg-brand-bg rounded-lg px-3 py-2 text-xs text-brand-muted font-mono break-all">
          {shareUrl}
        </div>
      </div>

      {/* Print Preview */}
      <div
        ref={printRef}
        className="bg-white rounded-xl border border-brand-border shadow-sm overflow-hidden print:shadow-none print:border-0"
      >
        {/* Print header */}
        <div
          className="px-6 py-4 text-white"
          style={{ backgroundColor: accentColor }}
        >
          <h2 className="text-lg font-bold">{list.name}</h2>
          <p className="text-sm opacity-80">
            Week of {formatDate(list.weekOf)} · {storeLabel(list.store)}
          </p>
          <p className="text-sm opacity-80">Estimated Total: {formatCurrency(total)}</p>
        </div>

        {/* Items */}
        <div className="p-6">
          {Object.entries(grouped).map(([category, items]) => (
            <div key={category} className="mb-6">
              <h3
                className="font-semibold text-sm uppercase tracking-wider mb-2 pb-1 border-b"
                style={{ color: accentColor, borderColor: accentColor }}
              >
                {category}
              </h3>
              <div className="grid grid-cols-1 gap-1">
                {items.map(item => (
                  <div key={item.id} className="flex justify-between items-center py-1">
                    <div className="flex items-center gap-2">
                      <div className={`w-4 h-4 border rounded flex items-center justify-center text-xs ${
                        item.checked ? 'border-green-500 bg-green-500 text-white' : 'border-gray-300'
                      }`}>
                        {item.checked && '✓'}
                      </div>
                      <span className={`text-sm ${item.checked ? 'line-through text-brand-muted' : 'text-brand-text'}`}>
                        {item.name}
                      </span>
                    </div>
                    <div className="text-right text-xs text-brand-muted">
                      <span>{item.quantity} {item.unit}</span>
                      <span className="ml-3">{formatCurrency(item.approxCost * item.quantity)}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}

          <div className="border-t border-brand-border pt-3 flex justify-between">
            <span className="font-semibold text-brand-text">Estimated Total</span>
            <span className="font-bold text-brand-text">{formatCurrency(total)}</span>
          </div>
        </div>

        <div className="px-6 py-3 bg-brand-bg border-t border-brand-border text-xs text-brand-muted">
          Generated by Family Grocery Tracker · {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
